"""add shares_full (ON DELETE CASCADE)

Revision ID: 0dcfdbd2f1c1
Revises: 56d25ed8de5d
Create Date: 2025-10-22 01:09:26.748047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0dcfdbd2f1c1'
down_revision: Union[str, None] = '56d25ed8de5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares_full',
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shares', sa.BigInteger(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], name="fk_shares_full_ticker", ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker_id', 'date', name="pk_shares_full")
    )
    op.create_index('ix_shares_full_ticker_id_date', 'shares_full', ['ticker_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shares_full_ticker_id_date', table_name='shares_full')
    op.drop_table('shares_full')
    # ### end Alembic commands ###
