"""Add valid column to ticker_status

Revision ID: 4f0b15b7553f
Revises: feafeb0e54ab
Create Date: 2025-10-19 15:26:14.776828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f0b15b7553f'
down_revision: Union[str, None] = 'feafeb0e54ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticker_status', sa.Column('valid', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ticker_status', 'valid')
