"""add stock_splits (ON DELETE CASCADE)

Revision ID: 56d25ed8de5d
Revises: be02cfce4090
Create Date: 2025-10-22 00:20:51.227854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '56d25ed8de5d'
down_revision: Union[str, None] = 'be02cfce4090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_splits',
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('factor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ticker_id', 'date')
    )
    op.create_index('ix_stock_splits_ticker_id_date', 'stock_splits', ['ticker_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_splits_ticker_id_date', table_name='stock_splits')
    op.drop_table('stock_splits')
    # ### end Alembic commands ###
