"""add maps_href to listing_details

Revision ID: 85de28a445c8
Revises: bd464ba23720
Create Date: 2025-09-16 18:54:47.369824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85de28a445c8'
down_revision: Union[str, None] = 'bd464ba23720'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_detail', sa.Column('maps_href', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
